dS2_lin2_test<-function(thetaN,alpha,y,exact=F,cpow=1)
{
  if(cpow==1)
  {
    dS1<-rexpar::dS2_lin2(thetaN,y)
  }
  if(cpow!=1)
  {
    dS1<-rexpar::dS2_lin2(thetaN,y,cpow=cpow,model="linARc")
  }
  NdS2<-NdS2<-sqrt(floor((length(y)-1)/2)-1)*(dS2-1/4)/sqrt(3/16)
  if(exact==T)
  {
    deci<-((dS2*(floor((length(y)-1)/2)-1))<qbinom(alpha,size=(floor((length(y)-1)/2)-1),prob=1/4))
  }
  else
  {
  deci<-(NdS2<qnorm(alpha))
  }
  list(TS=NdS2,phi=deci)
}