est_lin1<-function(y,maxit=25,candy=FALSE,acc=0.1,plots=FALSE,eps=0.0001,unique=TRUE,notion="dS")
{
  LT<-lin1_theta_eps(y,eps)
  sv<-median(LT)
  dists<-apply(LT,1,Ele_Norm,center=sv)
  cands<-LT[dists<quantile(dists,acc)]
  if(notion=="dS")
  {
  apply(cands,1,dS_lin1)->ev
  }
  if(notion=="dS1")
  {
    apply(cands,1,dS1_lin2,model="linAR1woI")->ev
  }
  if(notion=="dS2")
  {
    apply(cands,1,dS2_lin2,model="linAR1woI")->ev
  }
  if(notion=="dS3")
  {
    apply(cands,1,dS3_lin2,model="linAR1woI")->ev
  }
  
  se<-cands[ev==max(ev)]
  itc<-1
  
  for(i in 1:maxit)
  {
    itc<-itc+1
    sv<-se
    dists<-apply(LT,1,Ele_Norm,center=sv)
    cands<-LT[dists<quantile(dists,acc)]
    if(notion=="dS")
    {
      apply(cands,1,dS_lin1)->ev
    }
    if(notion=="dS1")
    {
      apply(cands,1,dS1_lin2,model="linAR1woI")->ev
    }
    if(notion=="dS2")
    {
      apply(cands,1,dS2_lin2,model="linAR1woI")->ev
    }
    if(notion=="dS3")
    {
      apply(cands,1,dS3_lin2,model="linAR1woI")->ev
    }
    se<-cands[ev==max(ev)]
    if(sv==se)
    {break}
    
  }
  max(ev)
  if(unique==TRUE)
  {
    se<-mean(se)
  }
  list(estimate=se,value=max(ev),numit=itc)
}